#! /bin/bash

if [ $# -gt 0 ]; then
    if [ "$1" == "bash" ]; then
        cmd="bash"
    else
        cmd="sqitch $*"
    fi
else
  cmd="sqitch"
fi

docker run -it --rm -v $PWD:/src sqitch $*

sudo chown $USER: $PWD -R

