dashboard:
  build: dashboard
  ports:
   - "8008:80"
  volumes:
   - dashboard/sites:/etc/nginx/sites-enabled
   - dashboard/www:/var/www
  links:
   - geoserver

db:
  image: kartoza/postgis
  hostname: postgis
  volumes:
    - ./postgres_data:/var/lib/postgresql
  environment:
    - USERNAME=docker
    - PASS=docker

geoserver:
  image: kartoza/geoserver
  hostname: geoserver
  volumes:
    - ./geoserver_data:/opt/geoserver/data_dir
  links:
    - db:db
