dashboard:
  build: dashboard
  ports:
   - "8008:80"
  volumes:
   - dashboard/sites:/etc/nginx/sites-enabled
   - dashboard/www:/var/www
  links:
   - geoserver

db:
  image: kartoza/postgis
  hostname: postgis
  ports:
   - "15432:5432"
  volumes:
    - ./postgres_data:/var/lib/postgresql
  environment:
    - USERNAME=docker
    - PASS=docker

geoserver:
  image: kartoza/geoserver
  hostname: geoserver
  volumes:
    - ./geoserver_data:/opt/geoserver/data_dir
  links:
    - db

django:
  build: django_project
  ports:
   - "8112:8000"
  volumes:
   - django_project/ENV:/ENV
   - django_project/start.sh:/start.sh
   - django_project/:/django_project
  links:
   - db
   - rabbitmq

rabbitmq:
  image: rabbitmq:3-management
  hostname: rabbitmq
  ports:
   - "15672:15672"
