django:
  image: mesa/django
  ports:
   - "8112:8000"
  volumes:
   - ENV:/ENV
   - start.sh:/start.sh
   - .:/django-project
  links:
   - db

db:
  image: kartoza/postgis
  hostname: postgis
  ports:
   - "15432:5432"
  volumes:
    - ./postgres_data:/var/lib/postgresql
  environment:
    - USERNAME=docker
    - PASS=docker

