#! /bin/bash

if [ $# -gt 0 ]; then
    if [ "$1" == "bash" ]; then
        cmd="bash"
    else
        cmd=
    fi
else
  cmd=
fi

source $PWD/ENV

docker run -it \
 -v $PWD/ENV:/ENV:ro \
 -p $POSTGREST_PORT:3000 \
 postgrest $cmd
