# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 10:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mesa.models


class Migration(migrations.Migration):

    initial = True
    dependencies = [
        ('mesa', '0003_performance'),
    ]
    operations = [
    migrations.RunSQL(

            sql = """
                CREATE OR REPLACE FUNCTION reset_firepixel_fireid(firepixel_id integer)
                RETURNS void AS
                $BODY$
                    BEGIN  
                    WITH row AS (
                        INSERT INTO mesa_firecluster(description, status, border) 
                        (
                            SELECT 'Firepixel #' || id, 'hotspot', (st_buffer(point, 2::double precision * GREATEST(hsize, vsize))) 
                            FROM mesa_firepixel WHERE id = firepixel_id
                        )
                        RETURNING id
                    )
                    UPDATE mesa_firepixel SET fire_id = (SELECT id FROM row) WHERE id = firepixel_id;
                    END
                $BODY$
                LANGUAGE plpgsql VOLATILE
                COST 1000;

                CREATE TABLE mesa_burned_area
                (
                    id serial NOT NULL,
                    burned_day numeric(9,0),
                    sensor character varying(20),
                    version character varying(20),
                    date timestamp without time zone,
                    the_geom geometry(MultiPolygon,4326),
                    CONSTRAINT mesa_burned_area_pkey PRIMARY KEY (id)   
                );

                CREATE INDEX mesa_burned_area_wkb_geometry_geom_idx
                ON mesa_burned_area
                USING gist
                (the_geom); 

            """,
            reverse_sql = """

                DROP FUNCTION reset_firepixel_fireid(integer);
                DROP TABLE mesa_burned_area;
                DROP INDEX mesa_burned_area_wkb_geometry_geom_idx;

            """,
        ),              
    ]


