# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 10:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mesa.models


class Migration(migrations.Migration):

    initial = True
    dependencies = [
        ('mesa', '0004_firepixel_relax_constraints'),
    ]
    operations = [
    migrations.RunSQL(

            sql = """
                CREATE OR REPLACE FUNCTION reset_firepixel_fireid(firepixel_id integer)
                RETURNS void AS
                $BODY$
                    BEGIN  
                    WITH row AS (
                        INSERT INTO mesa_firecluster(description, status, border) 
                        (
                            SELECT 'Firepixel #' || id, 'hotspot', (st_buffer(point, 2::double precision * GREATEST(hsize, vsize))) 
                            FROM mesa_firepixel WHERE id = firepixel_id
                        )
                        RETURNING id
                    )
                    UPDATE mesa_firepixel SET fire_id = (SELECT id FROM row) WHERE id = firepixel_id;
                    END
                $BODY$
                LANGUAGE plpgsql VOLATILE
                COST 1000;
            """,
            reverse_sql = """
                DROP FUNCTION reset_firepixel_fireid(integer);
            """,
        ),              
    ]
