#!/bin/bash

# Script to install MESA Wildfire software unto a vinilla Ubuntu machine

set -x

HERE=$(readlink -f `dirname $0`)
MESA_ROOT=$(readlink -f $HERE/..)
VOLUMES=$MESA_ROOT/volumes

export DEBIAN_FRONTEND=noninteractive

# General
apt-get update
apt-get upgrade -y
apt-get install -y git


# Install Docker - https://docs.docker.com/installation/ubuntulinux/
apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" >> /etc/apt/sources.list.d/docker.list
apt-get update
apt-get purge -y lxc-docker*
apt-cache policy docker-engine
sudo apt-get install -y docker-engine
sudo docker run hello-world


# Install GeoNode
git clone https://github.com/GeoNode/geonode
docker build -t geonode geonode
mkdir $VOLUMES/geonode_data/workspaces
cp -r $MESA_ROOT/admin/geoserver/mesa $VOLUMES/geonode_data/workspaces/


# Install PostGIS
docker pull kartoza/postgis


# Install Geoserver
#docker pull kartoza/geoserver


# Install RabbitMQ
docker pull rabbitmq:3-management


# Install Nginx
cd $MESA_ROOT/nginx
./build


# Install MESA Wildfire application
cd $MESA_ROOT/django_project
cp ENV.example ENV
./build
./manage migrate


# Install supervisord
# See: http://serverfault.com/questions/96499/how-to-automatically-start-supervisord-on-linux-ubuntu
apt-get install -y supervisor
cp $HERE/supervisord/init.d/supervisor /etc/init.d/supervisor
chmod +x /etc/init.d/supervisor

cd $HERE/supervisord
./update_conf

#FILES=$HERE/supervisord/conf.d/*
#for f in $FILES; do
#  TARGET=/etc/supervisor/conf.d/$(basename $f)
#  cat $f | sed -e "s|MESA_ROOT=\".*|MESA_ROOT=$MESA_ROOT|g" > $TARGET
#  echo "$f --> $TARGET"
#done;

update-rc.d supervisor defaults
service supervisor stop
service supervisor start
service supervisor status


