--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

SET search_path = public, pg_catalog;

--
-- Name: wmslayer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: afisuser
--

SELECT pg_catalog.setval('wmslayer_id_seq', 56, true);


--
-- Data for Name: wmslayer; Type: TABLE DATA; Schema: public; Owner: afisuser
--

COPY wmslayer (id, name, description, owner_id, min_scale, max_scale, is_visible, content_type_id, as_open_layer, url, layers, image_format_id, is_base_layer, is_transparent) FROM stdin;
24	MODIS Active Fire Archive	Archive of MODIS active fires from 2000. Beware size when making requests. These data are the observation centroid coordinates	2	35000000	250001	t	14	lyr24 = new OpenLayers.Layer.WMS(\n        'MODIS Active Fire Archive','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'openafis:af_modis_datetime',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 35000000,\n          maxScale: 250001\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr24.id] = 'lyr24'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	openafis:af_modis_datetime	1	f	t
25	MODIS Active Fires Last 48 Hours	MODIS Active Fires for the last 48 hour rolling period from now(). Observation centroids	2	35000000	250001	t	14	lyr25 = new OpenLayers.Layer.WMS(\n        'MODIS Active Fires Last 48 Hours','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'af_modis_datetime_48h',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 35000000,\n          maxScale: 250001\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr25.id] = 'lyr25'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	af_modis_datetime_48h	1	f	t
29	MODIS Active Fires Today	MODIS Active Fire pixel centroids since midnight	2	35000000	250001	t	14	lyr29 = new OpenLayers.Layer.WMS(\n        'MODIS Active Fires Today','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'af_modis_datetime_today',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 35000000,\n          maxScale: 250001\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr29.id] = 'lyr29'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	af_modis_datetime_today	1	f	t
30	MSG Active Fires Archive	MSG SEVIRI Active Fires Archive - careful of large size	2	35000000	1	t	14	lyr30 = new OpenLayers.Layer.WMS(\n        'MSG Active Fires Archive','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'af_msg_datetime',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 35000000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr30.id] = 'lyr30'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	af_msg_datetime	1	f	t
31	MSG Active Fires Last 48 Hours	MSG SEVIRI Active Fires for the last 48 hour rolling window	2	35000000	1	t	14	lyr31 = new OpenLayers.Layer.WMS(\n        'MSG Active Fires Last 48 Hours','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'af_msg_datetime_48h',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 35000000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr31.id] = 'lyr31'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	af_msg_datetime_48h	1	f	t
32	MSG Active Fires Today	MSG SEVIRI Active Fire since midnight	2	35000000	1	t	14	lyr32 = new OpenLayers.Layer.WMS(\n        'MSG Active Fires Today','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'af_msg_datetime_today',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 35000000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr32.id] = 'lyr32'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	af_msg_datetime_today	1	f	t
33	Eskom Transmission Lines	Eskom National Transmission Lines	2	2500000	1	t	14	lyr33 = new OpenLayers.Layer.WMS(\n        'Eskom Transmission Lines','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'national_lines',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 2500000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr33.id] = 'lyr33'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	national_lines	1	f	t
56	DAFdemo	MODIS data collected between 2008-08-01 00:00:00 and 2008-08-31 00:00:00	2	80000000	1	t	15	lyr56 = new OpenLayers.Layer.WMS(\n        'DAFdemo','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'openafis:af_modis_datetime',\n          transparent: 'true',\n          format: 'image/png',\n          filter: '<Filter><PropertyIsBetween><PropertyName>acqdatetime</PropertyName><LowerBoundary><Literal>2008-08-01T00:00:00</Literal></LowerBoundary><UpperBoundary><Literal>2008-08-31T00:00:00</Literal></UpperBoundary></PropertyIsBetween></Filter>'\n        },\n        {\n          reproject: true,\n          minScale: 80000000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n    gLayersDict[lyr56.id] = 'lyr56'; \n    \n    	http://afis.meraka.csir.co.za/geoserver/wms	openafis:af_modis_datetime	1	f	t
34	Eskom Transmission Towers	Eskom National Transmission Towers - careful of large dataset	2	250000	1	t	14	lyr34 = new OpenLayers.Layer.WMS(\n        'Eskom Transmission Towers','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'national_towers',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 250000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr34.id] = 'lyr34'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	national_towers	1	f	t
35	FPAs	Fire Protection Associations	2	3500000	1	t	14	lyr35 = new OpenLayers.Layer.WMS(\n        'FPAs','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'fpas',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 3500000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr35.id] = 'lyr35'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	fpas	1	f	t
36	Protected Areas	SANBI Protected Areas	2	3500000	1	t	14	lyr36 = new OpenLayers.Layer.WMS(\n        'Protected Areas','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'sanbi_protected_areas',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 3500000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr36.id] = 'lyr36'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	sanbi_protected_areas	1	f	t
37	Wind	Latest Wind data values form the network of WeatherSA automated weather stations around southern Africa	2	35000000	1	t	14	lyr37 = new OpenLayers.Layer.WMS(\n        'Wind','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'w_aws_join_latest_wind',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 35000000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr37.id] = 'lyr37'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	w_aws_join_latest_wind	1	f	t
39	MODIS Active Fire Pixel Archive	The full archive of MODIS Active Fire Detections, expanded to roughly represent the size of the fire detection. Be careful of huge data size	2	250000	1	t	14	lyr39 = new OpenLayers.Layer.WMS(\n        'MODIS Active Fire Pixel Archive','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'af_modis_pixel_datetime',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 250000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr39.id] = 'lyr39'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	af_modis_pixel_datetime	1	f	t
40	MODIS Active Fire Pixels Last 48 Hours	MODIS Active Fire Detections in the last 48 hour rolling window period, expanded to roughly represent the size of the fire detection.	2	250000	1	t	14	lyr40 = new OpenLayers.Layer.WMS(\n        'MODIS Active Fire Pixels Last 48 Hours','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'af_modis_pixel_datetime_48h',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 250000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr40.id] = 'lyr40'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	af_modis_pixel_datetime_48h	1	f	t
41	MODIS Active Fire Pixels Today	MODIS Active Fire Detections since midnight, expanded to roughly represent the size of the fire detection.	2	250000	1	t	14	lyr41 = new OpenLayers.Layer.WMS(\n        'MODIS Active Fire Pixels Today','http://afis.meraka.org.za/geoserver/wms',\n        {\n          layers: 'af_modis_pixel_datetime_today',\n          transparent: 'true',\n          format: 'image/png'\n        },\n        {\n          reproject: true,\n          minScale: 250000,\n          maxScale: 1\n        },\n        {\n          isBaseLayer: true\n        }\n      );\n      gLayersDict[lyr41.id] = 'lyr41'; \n      	http://afis.meraka.csir.co.za/geoserver/wms	af_modis_pixel_datetime_today	1	f	t
\.


--
-- PostgreSQL database dump complete
--

