#!/bin/bash

docker run -d --name geonode --link supervisor_postgis:postgis -p 8111:8000 -p 8080:8080 -v $PWD/local_settings.py:/geonode/geonode/local_settings.py -v $PWD/data:/geonode/geoserver/data geonode
