#!/bin/bash

ENV_PATH=`pwd`/../admin/ENV
source $ENV_PATH

docker run --name run_mesa_manage --link supervisor_postgis:postgis -v $ENV_PATH:/ENV -v `pwd`/start.sh:/start.sh -v `pwd`:/django_project -it --rm mesasadc/mesa_django:$BUILD_TAG /django_project/manage.py $*
