#!/bin/bash

docker run -it --rm -p 8112:8000 --name mesa_django --link mesa_db_1:db --link mesa_rabbitmq_1:rabbitmq -v $PWD/ENV:/ENV -v $PWD/start.sh:/start.sh -v $PWD:/django_project mesa/django $*


